### ISSUE TITLE
[ENHANCEMENT]: docker metadata

### ISSUE THREAD

**Issue by c0rydoras** [adfinis/outdated#364]
### Your proposed enhancement

Use docker/metadata-action@v5

### Enhancement Impact

- Metadata
- Labels generated from semver

### Additional context

something like this:

```yaml
...
      - name: Docker meta for API
        id: api-meta
        if: steps.semrel.outputs.version != ''
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/api
          flavor: |
            latest=auto
          tags: |
            type=semver,pattern={{version}},value=${{ steps.semrel.outputs.version }}
            type=semver,pattern={{major}}.{{minor}},value=${{ steps.semrel.outputs.version }}
            type=semver,pattern={{major}},value=${{ steps.semrel.outputs.version }}
          labels: |
            org.opencontainers.image.title=${{ github.event.repository.name }}
            org.opencontainers.image.description=${{ github.event.repository.description }}
            org.opencontainers.image.url=${{ github.event.repository.html_url }}
            org.opencontainers.image.source=${{ github.event.repository.clone_url }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.licenses=${{ github.event.repository.license.spdx_id }}

      - name: Docker meta for ember
        id: ember-meta
        if: steps.semrel.outputs.version != ''
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/ember
          flavor: |
            latest=auto
          tags: |
            type=semver,pattern={{version}},value=${{ steps.semrel.outputs.version }}
            type=semver,pattern={{major}}.{{minor}},value=${{ steps.semrel.outputs.version }}
            type=semver,pattern={{major}},value=${{ steps.semrel.outputs.version }}
          labels: |
            org.opencontainers.image.title=${{ github.event.repository.name }}
            org.opencontainers.image.description=${{ github.event.repository.description }}
            org.opencontainers.image.url=${{ github.event.repository.html_url }}
            org.opencontainers.image.source=${{ github.event.repository.clone_url }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.licenses=${{ github.event.repository.license.spdx_id }}

      - name: Build and Push API Docker Image
        if: steps.semrel.outputs.version != ''
        uses: docker/build-push-action@v5
        id: docker-api
        with:
          context: ./api/
          push: true
          tags: ${{ steps.api-meta.outputs.tags }}
          labels: |
            ${{ steps.api-meta.outputs.labels }}

      - name: Build and Push Ember Docker Image
        if: steps.semrel.outputs.version != ''
        uses: docker/build-push-action@v5
        id: docker-ember
        with:
          context: ./ember/
          push: true
          tags: ${{ steps.ember-meta.outputs.tags }}
          labels: |
            ${{ steps.ember-meta.outputs.labels }}
...
```

### Required

- [X] I have checked past issues to ensure that this isn't a duplicate.
